{% extends _layout %}

{% block content %}

An uncaught Exception was encountered

Type:        {{get_class(exception)}}
Message:     {{message}}
Filename:    {{exception.getFile()}}
Line Number: {{exception.getLine()}}

{% if defined('SHOW_DEBUG_BACKTRACE') and SHOW_DEBUG_BACKTRACE %}

Backtrace:
	{% for error in exception.getTrace() %}
		{% if error.file starts with realpath(BASEPATH) %}
		{% else %}
	File: {{error.file}}
	Line: {{error.line}}
	Function: {{error.function}}
		{% endif %}
	{% endfor %}
{% endif %}
{% endblock %}
